### ISSUE TITLE
Frozen-Flask is not compatible with Werkzeug 3.0.0

### ISSUE THREAD

**Issue by kris524** [Frozen-Flask/Frozen-Flask#129]
I was using `freeze.freeze()` and I got the following issue: `AttributeError: 'Map' object has no attribute 'charset'`
After looking at the Werkzeug documentation, I saw that `charset` has been deprecated.

**Comment by paulocoutinhox** [comment]
Hi,

I have the same error:

```
12:54:26.076 | Traceback (most recent call last):
-- | --
12:54:26.076 | File "kaktos.py", line 6, in <module>
12:54:26.077 | system.process_command()
12:54:26.077 | File "/opt/buildhome/repo/modules/system.py", line 121, in process_command
12:54:26.077 | run(command_params)
12:54:26.077 | File "/opt/buildhome/repo/modules/commands/build.py", line 12, in run
12:54:26.077 | system.build_pages()
12:54:26.078 | File "/opt/buildhome/repo/modules/system.py", line 82, in build_pages
12:54:26.078 | freezer_app.freeze()
12:54:26.078 | File "/opt/buildhome/.asdf/installs/python/3.8.18/lib/python3.8/site-packages/flask_frozen/__init__.py", line 205, in freeze
12:54:26.078 | return set(page.url for page in self.freeze_yield())
12:54:26.078 | File "/opt/buildhome/.asdf/installs/python/3.8.18/lib/python3.8/site-packages/flask_frozen/__init__.py", line 205, in <genexpr>
12:54:26.078 | return set(page.url for page in self.freeze_yield())
12:54:26.079 | File "/opt/buildhome/.asdf/installs/python/3.8.18/lib/python3.8/site-packages/flask_frozen/__init__.py", line 183, in freeze_yield
12:54:26.079 | for url, endpoint, last_modified in self._generate_all_urls():
12:54:26.079 | File "/opt/buildhome/.asdf/installs/python/3.8.18/lib/python3.8/site-packages/flask_frozen/__init__.py", line 232, in _generate_all_urls
12:54:26.079 | url_encoding = self.app.url_map.charset
12:54:26.079 | AttributeError: 'Map' object has no attribute 'charset'
```

In my project:

https://github.com/paulocoutinhox/kaktos

**Comment by paulocoutinhox** [comment]
This project is dead? Nobody answer.

I think that use w version 2 will cause other problem, because Flask3 was released:

```
3:21:56 PM: ERROR: flask 3.0.0 has requirement Werkzeug>=3.0.0, but you"ll have werkzeug 2.3.7 which is incompatible.
Installing collected packages: libsass, click, MarkupSafe, Jinja2, zipp, importlib-metadata, itsdangerous, werkzeug, blinker, flask, frozen-flask, six, tornado, livereload, ply, calmjs.parse, python-dotenv, dukpy, jmespath, urllib3, python-dateutil, botocore, s3transfer, boto3, colorama, pygemstones
```

**Comment by honzajavorek** [comment]
> This project is dead?

Short version, mostly yes. Long version [here](https://github.com/Frozen-Flask/Frozen-Flask/pull/130#issuecomment-1748247285).

Even if it wasn't dead, it's quite normal for the ecosystem of voluntarily maintained extensions to catch up slowly when a major breaking version of the main project gets released. New Flask is out for only 6 days. People have lives.

Please pin your dependencies to werkzeug < 3 until this gets resolved. There is already a Pull Request kick off in https://github.com/Frozen-Flask/Frozen-Flask/pull/130, which I think is quite nice for a project as dead as this one!
